---
disk: vda
okd: 
  name: "okd"
  ipaddr: "192.168.110.1"
helper:
  name: "helper"
  ipaddr: "192.168.110.9"
dns:
  domain: "bme.lab"
  clusterid: "bomar"
  forwarder1: "{{ ansible_dns.nameservers[0] }}"
  forwarder2: "8.8.8.8"
dhcp:
  router: "{{ ansible_default_ipv4.gateway }}"
  bcast: "{{ ansible_default_ipv4.broadcast }}"
  netmask: "{{ ansible_default_ipv4.netmask }}"
  poolstart: "192.168.110.80"
  poolend: "192.168.110.99"
  ipid: "{{ ansible_default_ipv4.network }}"
  netmaskid: "{{ ansible_default_ipv4.netmask }}"
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.110.110"
  macaddr: "52:54:00:f3:cd:dd"
masters:
  - name: "master0"
    ipaddr: "192.168.110.111"
    macaddr: "52:54:00:3e:b7:f7"
  - name: "master1"
    ipaddr: "192.168.110.112"
    macaddr: "52:54:00:0b:55:46"
  - name: "master2"
    ipaddr: "192.168.110.113"
    macaddr: "52:54:00:a8:99:b6"
workers:
  - name: "worker0"
    ipaddr: "192.168.110.114"
    macaddr: "52:54:00:26:8c:76"
  - name: "worker1"
    ipaddr: "192.168.110.115"
    macaddr: "52:54:00:3d:71:8c"
  - name: "worker2"
    ipaddr: "192.168.110.116"
    macaddr: "52:54:00:c4:7d:86"
  - name: "worker3"
    ipaddr: "192.168.110.117"
    macaddr: "52:54:00:00:5a:70"

setup_registry:
  deploy: true
  autosync_registry: true
  registry_image: docker.io/library/registry:2
  local_repo: "ocp4/okd"
  product_repo: "openshift"
  release_name: "okd"
  release_tag: "4.14.0-0.okd-2024-01-06-084517"
  registry_user: "admin"
  registry_password: "admin"

nfs:
  server: "192.168.110.9"
  path: "/shares/helper"

chronyconfig:
  enabled: true
  content:
    - server: helper.bomar.bme.lab
      options: iburst

machineconfig_path: ../machineconfig