#!/bin/bash

# Clean directories and files generated by Terraform
echo " Clean directories and files generated by Terraform ... "

rm -rf /root/okd-deployment/terraform/bootstrap/.terraform*
rm -rf /root/okd-deployment/terraform/bootstrap/terraform.tfstate*

rm -rf /root/okd-deployment/terraform/hypervisor/.terraform*
rm -rf /root/okd-deployment/terraform/hypervisor/terraform.tfstate*