#!/bin/bash

# Clean directories and files generated by Terraform

rm -rf terraform/bootstrap/.terraform
rm -rf terraform/bootstrap/terraform.tfstate*

rm -rf terraform/hypervisor/.terraform
rm -rf terraform/hypervisor/terraform.tfstate*