# This file denotes the base configuration for the OKD 4.x cluster deployment.

apiVersion: v1
baseDomain: buzz.lab
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: cluster-okd
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTIyN2EwZDMzZTRjNDM3MDk2ZGJlNWYxMGI3MzcxNGU6M1dOWDZLRFo5VFoxQVRITUFDQlRVRDJBS01GUFZQTjdIMlRNRlRDNkxNWUVIM0JHRzlXS1lRRUZBTFYzVFJBNw==","email":"boris-externe.assogba@edf.fr"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTIyN2EwZDMzZTRjNDM3MDk2ZGJlNWYxMGI3MzcxNGU6M1dOWDZLRFo5VFoxQVRITUFDQlRVRDJBS01GUFZQTjdIMlRNRlRDNkxNWUVIM0JHRzlXS1lRRUZBTFYzVFJBNw==","email":"boris-externe.assogba@edf.fr"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTQxZmNhYmJiLTc3ZTMtNDJlMy05OTBmLTEzODRlODI5OTRjMDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtORGd3TlRNME1tRXhZakkwTXpVNFlXTTROamRoTURNM056ZzFPVFkzT1NKOS5wTHo0VEVucEpJR0RnV1doc0x0Z3hmRXhROEJELVRXQThjdVpENGFldzE3QzdSUW53Rmh6N1h1VXphVWNZY211S2cwTUItU3llVVdyYm1Tb1dvTUt5bFpaZUlqRVNXdVQ4dkxKUFF6Z3BfTHVOT1gxcGplRjlqZWFmd2ZzcmNmQlBMRnBtUUI3VGhVbXVheTZJYUMwLWp0dWhqd0otNFUtSFYyRFZTSng2aHZwNU5NT2dhVTA4clZFc19QQmkzV2dnYWZhQnYtZnhvRzh3WmFoOU9VZHpVVHotMG16NjY0NHZkNnhhYkNoSWdnZWxyV1Nydm5IREc5RzhvSmM0NU1UMVEzSDlwN2p6UTN2R2twV1V6bHhwVE1RakM1eENRa3Jxa3JkMUFfNGVMRlE1dFRWMzFVdUtsa3ZrYmJQZGozZVJLRDRNTlJfTWY1N0FzbEFoNlA4NDZJU2dBOGEyWkVjS3BRRGxRbFBvaVBOa1kzdUVxNVhsRDlhQ0FGbjBZV2VYMW9fSHpwMFEwMk96bUxXWGlnTXM5R2FoSDN5VGMtendaNncwTXlkSTRwVDV5cDBxeG1UaXZSaU9GV2NLSGt3Tm5oVmhjTk5sT0gwWGlEdXRvMEtDQ1dfcjRCZ3lhMjFDS0w3a2FZQjZwWldYbnhzQUFsaFhId004QmpfQnVPUzMzcGRLcmhvZUhaWnprMHlJXzFYSVpjVVMxdVFrRS04aVhIZl9RT3FNb2Z2MFRzWV9uVndoZGZwMF9DVnhVaXpFWGo0MnVHVFc4SnBiVXkxX2d1RW8wMWJWMFUzVGU1NWR4bHhIWE1rNjZDdjNBOTh1WTBnVmpURnNTbEVhNGdwRjN5bll5MlBIeGl3dTNnSUgwak9aY3Jkd2tSd1dxQkhqNVB1c1E3OXdlaw==","email":"boris-externe.assogba@edf.fr"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTQxZmNhYmJiLTc3ZTMtNDJlMy05OTBmLTEzODRlODI5OTRjMDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtORGd3TlRNME1tRXhZakkwTXpVNFlXTTROamRoTURNM056ZzFPVFkzT1NKOS5wTHo0VEVucEpJR0RnV1doc0x0Z3hmRXhROEJELVRXQThjdVpENGFldzE3QzdSUW53Rmh6N1h1VXphVWNZY211S2cwTUItU3llVVdyYm1Tb1dvTUt5bFpaZUlqRVNXdVQ4dkxKUFF6Z3BfTHVOT1gxcGplRjlqZWFmd2ZzcmNmQlBMRnBtUUI3VGhVbXVheTZJYUMwLWp0dWhqd0otNFUtSFYyRFZTSng2aHZwNU5NT2dhVTA4clZFc19QQmkzV2dnYWZhQnYtZnhvRzh3WmFoOU9VZHpVVHotMG16NjY0NHZkNnhhYkNoSWdnZWxyV1Nydm5IREc5RzhvSmM0NU1UMVEzSDlwN2p6UTN2R2twV1V6bHhwVE1RakM1eENRa3Jxa3JkMUFfNGVMRlE1dFRWMzFVdUtsa3ZrYmJQZGozZVJLRDRNTlJfTWY1N0FzbEFoNlA4NDZJU2dBOGEyWkVjS3BRRGxRbFBvaVBOa1kzdUVxNVhsRDlhQ0FGbjBZV2VYMW9fSHpwMFEwMk96bUxXWGlnTXM5R2FoSDN5VGMtendaNncwTXlkSTRwVDV5cDBxeG1UaXZSaU9GV2NLSGt3Tm5oVmhjTk5sT0gwWGlEdXRvMEtDQ1dfcjRCZ3lhMjFDS0w3a2FZQjZwWldYbnhzQUFsaFhId004QmpfQnVPUzMzcGRLcmhvZUhaWnprMHlJXzFYSVpjVVMxdVFrRS04aVhIZl9RT3FNb2Z2MFRzWV9uVndoZGZwMF9DVnhVaXpFWGo0MnVHVFc4SnBiVXkxX2d1RW8wMWJWMFUzVGU1NWR4bHhIWE1rNjZDdjNBOTh1WTBnVmpURnNTbEVhNGdwRjN5bll5MlBIeGl3dTNnSUgwak9aY3Jkd2tSd1dxQkhqNVB1c1E3OXdlaw==","email":"boris-externe.assogba@edf.fr"},"registry.cluster-okd.buzz.lab:5000":{"auth":"YWRtaW46YWRtaW4=","email":"noemail@localhost"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDnSRJ9gQNos4GAg3XvLN0yhHF/HuNFMRBS4hF4Zny91TmRTLkb3+w2dQxelPVKymekqskhLepsbYGSh4647z3Jv0c7dwRglrUJcmWO47gHd0BlKAXjobR1v5dHnLbeDNPa1W+1MXc1bQOMAqV+zGR6ZmI+xC+kpRwcOeK4l1srWIKkAt0uA/b9PIxpaFoMmUuunWNlQMY0MfPQOyM2W6oU+fE6RRoF8cJDs6e2BuV46Y150nw8j2x8oTgXX7c8VFXyGTzU1Igbm2+28umnjcpw6PNI/zSYw4xik7Es96qLtIY5SKa2YGaqqg18CmHAu6dA/AvoVb2nGGklaZ+WMP6ZRP6pbYkdQQy3jTU/s7QIbMkuNsYaYVPY5WufoVKMPtykvXDxTQcGFL5iivDzCedcfWlJ91uOWdj83gkd+v/mc67dWHSm7kX6q40Fj7KOngHKUQ5KY6Fb44bC+C0Hb68CjbemJ4soa89+PmSYvkpnTYCzme3wKlm7eP+YlWHM9rNaguGPD84V+uV0bxNjMCcTy8BRZ9IsJbWIP9Vab9sEzTnUyc+OSBZlEdqieWDMKsu4ccJVBO9XNxZewPHQi9ig09NyhzrpwqBppCKx6RZYFZGb3AnbJM7+HZX1Wj4v9bSFxx+Sg9BIQ3pPjlRyis+ix1P3QbEYgvNjDk0cuG66Hw== helper-buzz-lab'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIFOjCCAyKgAwIBAgIUNoT+6OuUMSITw3TKqVbO2IeEZfMwDQYJKoZIhvcNAQEL
  BQAwKDEmMCQGA1UEAwwdcmVnaXN0cnkuY2x1c3Rlci1va2QuYnV6ei5sYWIwHhcN
  MjMwNzE2MjIwMDEzWhcNMzMwNzEzMjIwMDEzWjAoMSYwJAYDVQQDDB1yZWdpc3Ry
  eS5jbHVzdGVyLW9rZC5idXp6LmxhYjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
  AgoCggIBAIm+dMSgvPIrfFK9zPLmdnJVCgwJrQd1CV0LXbSr0Y6PFnbiDmOOzx8I
  axVmqL+oo7P3w5f/hM4WLB+qX7XeE/ON/O6OFJbeGbiWr/Jd2TRkuJ4mGdOrTDOj
  Gg3xgElGWIaI7uiCeycxNrsaNRoV5wGHj6Sgot38qDju7+QyCCPCSEGIVATq05JL
  S8fNTBctMU2LflT+VD7kllbeEtQbs4SKJCTEfsHx69on4u2PJhn/0fBfQ2TrFpnk
  kvi7pyEGQ1vRzgSQjZDzL1XEsxVLzPqI+FR0PgN41SkbYROn+sOIT46RoQQbjxDz
  b070DUFOpjQwt/PlDaqlqaG6ZfBu1Hh6Sc2TaSiX9ncHdR0Z+cbQU+nBGOE4Lxlb
  IpcW3QVDwuwRsdLaN7KSOG4sg9VbRETxE4F4ZHUkO3s/HYKc6dANxQxQPmfoUE+B
  yLPf8PASNpqSOugiJHB65SL7DZt4bm7hW7hlHx24si8HL/566WWgIyV++VITWwMN
  4Dt6kGYe7NNgttPOTcSU5+ZTEm8k1lC7UuG4I22shh+NLUCpCdr3zYTsN29muVsG
  Xu+ncuIdjEmbyXH0bnvtgBUU3SisRXXu9+O+dPBD0sB39estKrVQPdqC2xVpkUpx
  chiU/SkEtTJ1ZFPd6AAkouKwLnieacaFYF9nijYw2/4jI4NktyTTAgMBAAGjXDBa
  MCgGA1UdEQQhMB+CHXJlZ2lzdHJ5LmNsdXN0ZXItb2tkLmJ1enoubGFiMA8GA1Ud
  EwEB/wQFMAMBAf8wHQYDVR0OBBYEFHq9okTut2kmTt1C3kwrWmHmKC1gMA0GCSqG
  SIb3DQEBCwUAA4ICAQAcx7KQbqufAVED+Pk8svJbHwMHcTsmlVzd0d2ITj3/YeH3
  cUlUk8krSNs4L2ttsUEZjkFQQS65xjrvVJlH3qRx1cAGxXe/sepmeNSISvSNg8bV
  JK4DMOs5JbckePTzAa+fK0c9+KjzJT1P2oDMyxe7LDp2qIsmocItlL+ewj1ShP9h
  RhCUxhR0GRaCIyZ+VOIt7BY8NBjcNGBEBil+yrfwbV/hrUdSO8o47ApygSqABT2j
  PwWh8oFyClLa+L30DujgMk11Oe1ERUa481UABSUtSSUeS4dusmuT1LoyXt1iPaGA
  t4q25UDVG9L/7+pX/NIsQolmuHb/aajEnTdZg1ACAkQrgBvpJjv34OVMtfMINjrH
  VDdCx7HgStiYM7d18EKBZVvr1eVjtm7e1QmV09DEHpBblWhk2yLJsKH5b5AHfBGY
  IWgqx2cyn9QaoHi8gKdmR2SsVcIhAf+uVEtWNDooEBLFHdFq89Ae5Oi1K6bBesmV
  eXAGnTBy4wZau1zNEYoqsRm/1szDvD3EOKWfwrWi/HlMTvVpM1UJOhFQk6gSXnAh
  8WecPwAT64LPf5dzrJymM+VV57jLjWn9VmU5u0eEL1oDdWL0Qu8jMTivpGv/IDzR
  eqySTviuaDYWYzdY7eiVGPEKXxvkR0oPQ7VxLlIsXhaItYPVre0rVXpXKSbLnw==
  -----END CERTIFICATE-----
imageContentSources:
- mirrors: 
  - registry.cluster-okd.buzz.lab:5000/ocp4/okd
  source: quay.io/openshift/okd
- mirrors: 
  - registry.cluster-okd.buzz.lab:5000/ocp4/okd
  source: quay.io/openshift/okd-content