apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: update-service-subscription
  namespace: openshift-update-service
spec:
  channel: v1
  installPlanApproval: "Manual"
  source: "redhat-operator-index-4-12" 
  sourceNamespace: "openshift-marketplace"
  name: "cincinnati-operator"
